baseURL = "https://sre-france.github.io/"
languageCode = "en-us"
title = "SRE France"
theme = "beautifulhugo"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[minify]
  disableHTML = true

[Params]
  homeTitle = "SRE France"
  subtitle = "Site reliability engineers in France"
  mainSections = ["post","posts"]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

[[Params.bigimg]]
  src = "img/bigimg-01.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-02.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-03.webp"
  desc = ""
  position = "center top"


[Author]
  website = "https://sre-france.github.io/"
  github = "sre-france"
  telegram = "joinchat/UtlUno6ukr0r6v6I"

[[menu.main]]
    name = "Meetups"
    url = "tags/meetup/"
    weight = 1

[[menu.main]]
    name = "Github"
    url = "https://github.com/sre-france/"
    weight = 2

[[menu.main]]
    name = "Job Board"
    url = "page/job-board/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
