baseURL = "https://sre-paris.github.io/"
languageCode = "en-us"
title = "SRE Paris"
theme = "beautifulhugo"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[Params]
  homeTitle = "SRE Paris"
  subtitle = "Site reliability engineers around Paris"
  mainSections = ["post","posts"]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true

[[Params.bigimg]]
  src = "img/bigimg-01.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-02.webp"
  desc = ""
  position = "center top"
[[Params.bigimg]]
  src = "img/bigimg-03.webp"
  desc = ""
  position = "center top"


[Author]
  website = "https://sre-paris.github.io/"
  github = "sre-paris"
  telegram = "joinchat/HjS_51LZVJ6cJ-D3K-r-iA"

[[menu.main]]
    name = "Meetups"
    url = "tags/meetup/"
    weight = 1

[[menu.main]]
    name = "Github"
    url = "https://github.com/sre-paris/"
    weight = 2

[[menu.main]]
    name = "Job Board"
    url = "page/job-board/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
